#fan:
#  - platform: xiaomi_airpurifier
#    name: Xiaomi Air Purifier 2
#    host: 192.168.8.112
#    token: 9c9aa22fed0f6d449f4e1f648844748c

fan:
  - platform: xiaomi_miio
    name: Xiaomi Air Purifier 2
    host: 192.168.31.174
    token: 9c9aa22fed0f6d449f4e1f648844748c

sensor:
  - platform: template
    sensors:
      xiaomi_ap_aqi:
        friendly_name: 空气质量
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.aqi }}"
        unit_of_measurement: AQI
      xiaomi_ap_temp:
        friendly_name: 温度
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.temperature }}"
        unit_of_measurement: °C
      xiaomi_ap_humid:
        friendly_name: 湿度
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.humidity }}"
        unit_of_measurement: "%"
      xiaomi_ap_filter_used:
        friendly_name: 滤芯使用时长
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.filter_hours_used}}"
        unit_of_measurement: H
      xiaomi_ap_filter_life:
        friendly_name: 滤芯寿命
        value_template: "{{ states.fan.xiaomi_air_purifier_2.attributes.filter_life_remaining}}"
        unit_of_measurement: "%"

switch:
  - platform: template
    switches:
      xiaomi_ap_buzzer:
        value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_2', 'buzzer', true) }}"
        turn_on:
          service: fan.xiaomi_miio_set_buzzer_on
          entity_id: fan.xiaomi_air_purifier_2
        turn_off:
          service: fan.xiaomi_miio_set_buzzer_off
          entity_id: fan.xiaomi_air_purifier_2

input_select:
  xiaomi_ap_mode:
    name: 模式
    icon: mdi:fan
    options:
      - "自动"
      - "睡眠"
      - "最爱"
      - "待机"
  xiaomi_ap_led:
    name: LED灯
    icon: mdi:led-on
    options:
      - "亮光"
      - "微光"
      - "关闭"


group:
  xiaomi_air_purifier:
    name: 小米空净
    view: no
    control: hidden
    entities:
      - fan.xiaomi_air_purifier_2
      - switch.xiaomi_ap_buzzer
      - sensor.xiaomi_ap_aqi
      - sensor.xiaomi_ap_temp
      - sensor.xiaomi_ap_humid
      - sensor.xiaomi_ap_filter_used
      - sensor.xiaomi_ap_filter_life
      - input_select.xiaomi_ap_mode
      - input_select.xiaomi_ap_led
     
automation:
  - alias: xiaomi_ap_get_mode
    initial_state: true
    trigger:
      platform: time_pattern
      seconds: /5
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.xiaomi_ap_mode
        option: >
          {% if states.fan.xiaomi_air_purifier_2.attributes.mode == "auto" %}自动
          {% elif states.fan.xiaomi_air_purifier_2.attributes.mode == "silent" %}睡眠
          {% elif states.fan.xiaomi_air_purifier_2.attributes.mode == "favorite" %}最爱
          {% elif states.fan.xiaomi_air_purifier_2.attributes.mode == "idle" %}待机
          {% endif %}

  - alias: xiaomi_ap_set_mode
    initial_state: true
    trigger:
      platform: state
      entity_id: input_select.xiaomi_ap_mode
    action:
      service: fan.turn_on
      data_template:
        entity_id: fan.xiaomi_air_purifier_2
        speed: >
          {% if states.input_select.xiaomi_ap_mode.state == "自动" %}Auto
          {% elif states.input_select.xiaomi_ap_mode.state == "睡眠" %}Silent
          {% elif states.input_select.xiaomi_ap_mode.state == "最爱" %}Favorite
          {% elif states.input_select.xiaomi_ap_mode.state == "待机" %}Idle
          {% endif %}

  - alias: xiaomi_ap_get_led
    initial_state: true
    trigger:
      platform: time_pattern
      seconds: /5
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.xiaomi_ap_led
        option: >
          {% if states.fan.xiaomi_air_purifier_2.attributes.led_brightness == 0 %}亮光
          {% elif states.fan.xiaomi_air_purifier_2.attributes.led_brightness == 1 %}微光
          {% elif states.fan.xiaomi_air_purifier_2.attributes.led_brightness == 2 %}关闭
          {% endif %}

  - alias: xiaomi_ap_set_led
    initial_state: true
    trigger:
      platform: state
      entity_id: input_select.xiaomi_ap_led
    action:
      service: fan.xiaomi_miio_set_led_brightness
      data_template:
        entity_id: fan.xiaomi_air_purifier_2
        brightness: >
          {% if states.input_select.xiaomi_ap_led.state == "亮光" %}0
          {% elif states.input_select.xiaomi_ap_led.state == "微光" %}1
          {% elif states.input_select.xiaomi_ap_led.state == "关闭" %}2
          {% endif %}

homeassistant:
  customize:
    fan.xiaomi_air_purifier_2:
      friendly_name: 空净开关
      extra_badge:
        entity_id: sensor.xiaomi_ap_aqi
      extra_data_template: 滤芯已用${attributes.filter_hours_used}小时，剩余${attributes.filter_life_remaining}%
    switch.xiaomi_ap_buzzer:
      icon: mdi:volume-high
      friendly_name: 提示音
    sensor.xiaomi_ap_aqi:
      icon: mdi:blur
    sensor.xiaomi_ap_humid:
      icon: mdi:water-percent

